### ISSUE TITLE
Hoping to watch my US TV in UK

### ISSUE THREAD

**Issue by lou-cucci** [simeoncran/hdhomerun_proxy#1]
Hi 

Thanks for writing this .. I am trying to figure out what needs to be installed on my PCs to get this working..

What is an app proxy?  Do I need to have an Azure account?
Do I need Docker installed on both PCs?

Thanks

Lou

**Comment by simeoncran** [comment]
> Thanks for writing this .. I am trying to figure out what needs to be installed on my PCs to get this working..
> 
> 
> 
> What is an app proxy?  Do I need to have an Azure account?
> 
> Do I need Docker installed on both PCs?

Assuming you have a working HDHomeRun tuner running on your US network, the first thing you need is a way to connect to that network from the UK. For that I use a WireGuard connection. If that's working, you should be able to connect from a web browser in the UK to the status web page on your HDHomeRun tuner in the US. However that's not sufficient for HDHomeRun apps to connect to the tuner because they use "broadcast packets" to find the address of the tuner on the network, and those only work between devices on the same network. The scripts here solve that problem by passing the broadcast packets between the 2 (UK and US in your case) networks.

So, first question, do you have a way to connect to your US HDHomeRun tuner's status web page from a browser connected to your network in the UK?

The "app proxy" is the script that will run on a computer on your US network that acts as if it is an HDHomeRun app on that network and will pass the broadcast packets to the HDHomeRun tuner on that network. The "tuner proxy" is the script that will run on a computer on your UK network that acts as if it is an HDHomeRun tuner on that network. The "app proxy" and the "tuner proxy" connect to each other and pass the broadcast packets from one network to the other.

This solution doesn't need or use Azure or any other cloud provider. You don't need Docker - I just use that because it's a convenient way for me to specify the configuration of a Python script and to have it start automatically. You could just install Python on a computer in each network and run the the Python scripts from the command line.

**Comment by lou-cucci** [comment]
Thanks … I have a working HDHomeRun tuner running on your US network … I connect via VPN from my US network to UK network..


When I am connect to my VPN in the UK and go to the IP address of the HDHomeRUN I can see the menu



What version of Python should I use and the modules.. do you have a requirements.txt file?

Thanks

Lou

**Comment by simeoncran** [comment]
I'm just using the latest Python in the Docker repo which is probably at least 3.9 but it shouldn't matter too much. Probably any 3.x version will work. No extra libraries are needed. You should be able to just run the scripts in a vanilla Python install. 

Run the tuner proxy script on your network in the UK and the app proxy script on the network in the US and start an HDHomeRun app on the UK network and see what happens. Paste the output here if it doesn't seem to work.

 If it gets tricky to figure out I'll add some debugging output to the scripts to help us diagnose things.

**Comment by lou-cucci** [comment]
Thank you

**Comment by simeoncran** [comment]
I've updated the docs and removed the confusing docker scripts to hopefully make this more simple for you and the next person.

I'm really interested to know whether you are able to get this going, and happy to help if you are still having difficulty.

**Comment by lou-cucci** [comment]
Thank you … I got emby to work for $5 /month so I am using that at the moment.. I will give your solution a go over the weekend

**Comment by simeoncran** [comment]
Closing because of no further comment here.
