### ISSUE TITLE
Windows client disconnected from Linux server over Tailscale

### ISSUE THREAD

**Issue by voltagex** [simeoncran/hdhomerun_proxy#2]
Note: to get `hdhomerun_tuner_proxy.py` to work on Windows I needed to change

```
            udp_transport, _udp_protocol = await loop.create_datagram_endpoint(
                lambda: UdpProtocol(),
                local_addr=('255.255.255.255', HDHOMERUN_DISCOVER_UDP_PORT),
                reuse_port=True,
                allow_broadcast=True)
```

to `reuse_port=False`, so this might be the cause of the issue.

```
PS C:\git\hdhomerun_proxy> python3.exe .\hdhomerun_tuner_proxy.py 10.0.0.2
Connecting to app proxy at 10.0.0.2...
Connected to app proxy: 10.0.0.2:65001
Disconnected
The server closed the connection
Attempting reconnection ...
Connecting to app proxy at 10.0.0.2...
Connected to app proxy: 10.0.0.2:65001
Disconnected
The server closed the connection
Attempting reconnection ...
Connecting to app proxy at 10.0.0.2...
Connected to app proxy: 10.0.0.2:65001
Disconnected
The server closed the connection
```

And the server can see the connections coming in

```
Tuner proxy at 10.0.0.1:50488 connected
Tuner proxy at 10.0.0.1:47408 connected
Tuner proxy at 10.0.0.1:47418 connected
Tuner proxy at 10.0.0.1:47430 connected
Tuner proxy at 10.0.0.1:36174 connected
```

setting a DEBUG environment variable at either end doesn't show any other details.

**Comment by simeoncran** [comment]
This now works on Windows, although I couldn't get the HDHomeRun app to work if it was running on the same machine as the hdhomerun_tuner_proxy. Not sure if that's a Windows issue or an HDHomeRun app issue or something else. For now that scenario is just unsupported by the code here, but maybe it can be made to work.

For reference, the problem is that there isn't a way (that I could find) to bind UDP to the broadcast address (255.255.255.255) on Windows with Python asyncio. The workaround is to bind to "0.0.0.0" and accept any UDP packet set to port 65001 rather than just broadcast packets. So that's what the code now does on Windows.

It also was swallowing some exceptions, which wasted my time and yours - so it does less of that now. :-)
